@baseUrl = http://localhost:3333/api

###

# Health
# @name Health
GET {{baseUrl}}/health

###

# Verify Token
# @name verifyToken
GET {{baseUrl}}/auth/validate
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

### POST

# Create User
# @name createUser
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "admin",
  "email": "admin@example.com",
  "password": "123456",
  "role": "admin"
}

###

# Login
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "123456"
}

###

# Deactivate User
# @name deactivateUser
POST {{baseUrl}}/users/{{userId}}/deactivate
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
  "deactivated_reason": "Deactivate by admin for test"
}

### GET

# Capture the ID of the user created to use in the next requests
@userId = {{createUser.response.body.userId}}

###

# Capture the ID of the deactivation created to use in the next requests
@deactivatedId = {{deactivateUser.response.body.id}}

###

# Get All Users
# @name getAllUsers
GET {{baseUrl}}/users
Authorization: Bearer {{login.response.body.token}}

###

# Get User By ID
# @name getUserById
GET {{baseUrl}}/users/{{userId}}
Authorization: Bearer {{login.response.body.token}}

###

# Get Activated Users
# @name getActivatedUsers
GET {{baseUrl}}/users/activated
Authorization: Bearer {{login.response.body.token}}

###

# Get Disabled Users
# @name getDeactivatedUsers
GET {{baseUrl}}/users/deactivated
Authorization: Bearer {{login.response.body.token}}

###

# Get Deactivated User
# @name getDeactivatedUser
GET {{baseUrl}}/users/{{userId}}/deactivated
Authorization: Bearer {{login.response.body.token}}

###

# Get Deactivations
# @name getDeactivations
GET {{baseUrl}}/deactivations
Authorization: Bearer {{login.response.body.token}}

###

# Get User Deactivation History
# @name getUserDeactivationHistory
GET {{baseUrl}}/users/{{userId}}/deactivation-history?field=deactivation_reasons,deactivation_dates,reactivation_reasons,reactivation_dates
Authorization: Bearer {{login.response.body.token}}

###

# Get Deactivations History
# @name getDeactivationsHistory
GET {{baseUrl}}/deactivation-history
Authorization: Bearer {{login.response.body.token}}

### UPDATE

# Update User
# @name updateUser
PUT {{baseUrl}}/users/{{userId}}
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
  "name": "Kaique Bezerra"
}

###

# Reactivate User
# @name reactivateUser
PUT {{baseUrl}}/users/{{userId}}/reactivate
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
  "reactivated_reason": "Reactivated by admin for test"
}

### DELETE

# Delete User
# @name deleteUser
DELETE {{baseUrl}}/users/{{userId}}
Authorization: Bearer {{login.response.body.token}}

###

# Delete Deactivated User
# @name deleteDeactivatedUser
DELETE {{baseUrl}}/users/{{deactivatedId}}/deactivated
Authorization: Bearer {{login.response.body.token}}

###

# Get user Gemini
# @name getUserGemini
POST {{baseUrl}}/users/gemini
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
  "email": "kaique@example.com"
}