// src/http/routes/users/get-user-by-email-gemini.ts
import type { FastifyPluginCallbackZod } from "fastify-type-provider-zod";
import z from "zod";
import { eq } from "drizzle-orm";
import { authMiddleware } from "../../../middlewares/auth-middleware.ts";
import { db } from "../../../db/connection.ts";
import { schema } from "../../../db/schema/index.ts";
import {
  describeUserWithGemini,
  validateEmailWithGemini,
} from "../../../services/gemini.ts";

export const getUserByEmailGeminiRoute: FastifyPluginCallbackZod = (app) => {
  app.post(
    "/api/users/gemini",
    {
      preHandler: [authMiddleware],
      schema: {
        tags: ["Users"],
        summary: "Get user by email via Gemini",
        description:
          "Receives an email, validates with Gemini and returns the user from the database + description generated by Gemini, including deactivated status.",
        body: z.object({
          email: z.email(),
        }),
        response: {
          200: z.object({
            message: z.string(),
            user: z.object({
              id: z.uuid(),
              name: z.string(),
              email: z.email(),
              role: z.string(),
              created_at: z.date(),
              updated_at: z.date().nullable(),
              deactivated: z.boolean(),
            }),
          }),
          400: z.object({ message: z.string() }),
          404: z.object({ message: z.string().default("User not found") }),
          500: z.object({
            message: z.string().default("Internal server error"),
          }),
        },
      },
    },
    async (request, reply) => {
      const { email } = request.body;

      try {
        const geminiEmail = await validateEmailWithGemini(email);

        if (geminiEmail === "invalid") {
          return reply.status(400).send({ message: "Invalid email" });
        }

        const result = await db
          .select({
            id: schema.users.id,
            name: schema.users.name,
            email: schema.users.email,
            role: schema.users.role,
            created_at: schema.users.created_at,
            updated_at: schema.users.updated_at,
            deactivated: schema.deactivated_users.id, // vamos usar para saber se existe
            reactivated_at: schema.deactivated_users.reactivated_at,
          })
          .from(schema.users)
          .leftJoin(
            schema.deactivated_users,
            eq(schema.deactivated_users.user_id, schema.users.id)
          )
          .where(eq(schema.users.email, geminiEmail))
          .limit(1);

        if (result.length === 0) {
          return reply.status(404).send({ message: "User not found" });
        }

        const user = result[0];

        // transforma em booleano: se existe deactivated_users sem reactivated_at → true
        const isDeactivated =
          user.deactivated != null &&
          user.reactivated_at === null;

        const message = await describeUserWithGemini(user);

        return reply.status(200).send({
          message,
          user: {
            id: user.id,
            name: user.name,
            email: user.email,
            role: user.role,
            created_at: user.created_at,
            updated_at: user.updated_at,
            deactivated: isDeactivated,
          },
        });
      } catch (error) {
        console.error("Get user by email via Gemini error:", error);
        return reply.status(500).send({ message: "Internal server error" });
      }
    }
  );
};
